services:
  meta-ads:
    restart: unless-stopped
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    image: meta-ads-extraction
    container_name: meta-ads-extraction
    networks:
      - scrapper-network
    environment:
      APP_ENV: prod
      PROXY_SERVER: ${PROXY_SERVER}

      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_HOST: ${MONGO_HOST}

networks:
  scrapper-network:
    name: scrapper-network
